test: added deserialization tests for `NodeContent`
whynotmake-it/figmage pull request #107
Opened 2024-05-04 10:01 UTC by timcreatedit

## Description

## Checklist

- [X] My PR title is in the style of [conventional commits](https://www.conventionalcommits.org/)
- [X] All public facing APIs are documented with [dartdoc](https://dart.dev/guides/language/effective-dart/documentation)
- [X] I have added tests to cover my changes

2024-05-04 11:13 UTC, JesperBllnbm requested changes

2024-05-04 11:13 UTC, JesperBllnbm commented on packages/figma_variables_api/test/src/dto/nodes/node_content_test.dart
> +      test('should not be equal if any property is different', () {
ahm, is this a oversight? Seems to be the same test as above..

2024-05-04 11:13 UTC, JesperBllnbm commented on packages/figma_variables_api/test/src/dto/nodes/node_content_test.dart
> +          'document': null,
Has document its own toJson and fromJson test?

2024-05-04 11:13 UTC, JesperBllnbm commented on packages/figma_variables_api/test/src/dto/nodes/node_content_test.dart
> +  setUp(() {});
Has this any effect?

2024-05-04 11:15 UTC, timcreatedit commented on packages/figma_variables_api/test/src/dto/nodes/node_content_test.dart
> +  setUp(() {});
Nope, should've been deleted!

2024-05-04 11:16 UTC, timcreatedit commented on packages/figma_variables_api/test/src/dto/nodes/node_content_test.dart
> +      test('should not be equal if any property is different', () {
Haha you're right, I just trusted copilot, mb

2024-05-27 09:16 UTC, timcreatedit commented on packages/figma_variables_api/test/src/dto/nodes/node_content_test.dart
> +          'document': null,
Not really, but it's part of package:figma, so not our job here

2024-05-31 09:17 UTC, merged