Feat/pull assets from figma
whynotmake-it/figmage pull request #162
Opened 2024-11-09 14:50 UTC by JesperBllnbm

## Description

Allows to download image assets from Figma directly into the package.

## Checklist

- [X] My PR title is in the style of [conventional commits](https://www.conventionalcommits.org/)
- [X] All public facing APIs are documented with [dartdoc](https://dart.dev/guides/language/effective-dart/documentation)
- [X] I have added tests to cover my changes

2024-12-15 15:47 UTC, timcreatedit requested changes

2024-12-15 15:47 UTC, timcreatedit commented on website/src/content/docs/reference/configuration-options.mdx
>  See the [Filtering generated Tokens](#filtering-generated-tokens) section for more information.
Add to main example with hint?

2024-12-15 15:47 UTC, timcreatedit commented on test/src/data/generators/file_generators/asset_file_generator_test.dart
> +  AssetImage get exampleNamePngImage => AssetImage(exampleNamePng, package: 'test_package');
Static

2024-12-15 15:47 UTC, timcreatedit commented on test/src/data/generators/file_generators/test.dart
Delete

2024-12-15 15:47 UTC, timcreatedit commented on lib/src/domain/providers/figmage_package_generator_providers.dart
> +);
Do we need this logic in here?

2024-12-15 15:47 UTC, timcreatedit commented on lib/src/data/repositories/figma_assets_repository.dart
> +        }
I would prefer extracting this into a separate function, e.g. `Future<File?> _downloadImage(String url)`

2024-12-15 15:47 UTC, timcreatedit commented on lib/src/data/repositories/figma_assets_repository.dart
> +}
Nit: Never type is fancy but I would prefer `throw _convertFigmaException(FigmaException)`, because I think it makes the code up top more explicit.

2024-12-15 15:47 UTC, timcreatedit commented on lib/src/data/repositories/figma_assets_repository.dart
> +      .expand((setting) => setting.scales.where((s) => s >= 0.01 && s <= 4))
Nit: these values could be constants, since we reuse them multiple times

2024-12-15 15:47 UTC, timcreatedit commented on lib/src/domain/models/config/config.dart
> +  List<Object?> get props => [name, scales];
I **think** we need to write `...scales` here so we have the proper comparison. Not sure though

2024-12-15 15:47 UTC, timcreatedit commented on lib/src/data/generators/file_generators/asset_file_generator.dart
> +  final Map<String, List<String>> assets;
Why do we always use `String` for the file path? I think `File` as a type is a bit more descriptive and makes it much more readable what we're dealing with here.

2024-12-15 15:47 UTC, timcreatedit commented on lib/src/data/generators/assets/asset_class_generator.dart
> +  final Map<String, List<String>> assets;
`File` here as well if possible

2024-12-15 15:47 UTC, timcreatedit commented on lib/src/data/generators/assets/asset_class_generator.dart
> +                    ..returns = refer('AssetImage')
static true?

2024-12-15 15:47 UTC, timcreatedit commented on lib/src/data/generators/assets/asset_class_generator.dart
> +            assets.entries.expand((entry) {
`assets.values`?

2024-12-15 15:47 UTC, timcreatedit commented on lib/src/data/generators/assets/asset_class_generator.dart
> +              });
```dart
[
  for (final MapEntry(key: id, value: files) in assets.entries)
   files.map(...) 
]
```

2024-12-15 15:47 UTC, timcreatedit commented on lib/src/data/generators/assets/asset_class_generator.dart
> +                ..assignment = const Code("'assets/'"),
`literal()`? Not sure if true

2024-12-15 21:27 UTC, JesperBllnbm commented on pubspec.yaml
> +  http: ^1.2.2
FigmaAssetsRepository
`final response = await http.get(Uri.parse(url));` line 89
Or did you mean something else?

2024-12-15 21:33 UTC, JesperBllnbm commented on lib/src/domain/providers/figmage_package_generator_providers.dart
> +);
Moved into a separate file

2024-12-15 22:24 UTC, JesperBllnbm commented on lib/src/data/generators/assets/asset_class_generator.dart
> +                ..assignment = const Code("'assets/'"),
I tried but,..
```sh
A value of type 'Expression' can't be assigned to a variable of type 'Code?'.
Try changing the type of the variable, or casting the right-hand type to 'Code?'
```

2024-12-15 22:24 UTC, JesperBllnbm commented on lib/src/data/generators/assets/asset_class_generator.dart
> +  final Map<String, List<String>> assets;
as mentioned before we just pass the file name around

2025-01-04 09:52 UTC, timcreatedit commented on pubspec.yaml
> +  http: ^1.2.2
My bad, I had this as a reminder to myself and forgot to delete it 🌝

2025-01-04 09:52 UTC, timcreatedit approved these changes

2025-01-04 09:56 UTC, merged