fix: generator tries to fit all variable collections into one class
whynotmake-it/figmage pull request #42
Opened 2023-12-26 12:49 UTC by JesperBllnbm

## Description

- multiple classes in one file for each generator
- use collection names instead of IDs for named constructors
- some general cleanup

## Checklist

- [x] My PR title is in the style of [conventional commits](https://www.conventionalcommits.org/)
- [x] All public facing APIs are documented with [dartdoc](https://dart.dev/guides/language/effective-dart/documentation)
- [x] I have added tests to cover my changes

2023-12-27 10:46 UTC, timcreatedit requested changes

2023-12-27 10:46 UTC, timcreatedit commented on lib/src/commands/shared/generation_notifier.dart
> +
hatte eigentlich extra alles aus dem notifier raus refactored damit der diese ganzen implementation details nicht braucht. So kann man jetzt zb den Teil der code genration nicht mehr isoliert testen

2023-12-27 10:46 UTC, timcreatedit commented on lib/src/domain/generators/theme_class_generator.dart
> +/// {@template generatorResult}
das `@template` brauchts hier nicht, ist ja nur relevant wenn mans beim constructor wiederverwenden will

2023-12-27 10:46 UTC, timcreatedit commented on lib/src/domain/models/style/design_style.dart
> +  String get collectionName => name.split('/').first;
Wollen wir das immer so? Werden so jetzt nicht potenziell viel zu viele classes generiert, z.B. wenn man styles gar nicht in collections eingeteilt sind bekommt doch jetzt jeder Style seine eigene Klasse oder? Hätte fast gesagt das ist vllt by default immer `""`

2023-12-27 10:46 UTC, timcreatedit commented on lib/src/domain/models/variable/variable.dart
> +      );
Wollte das von anfang an so aber hatte es nicht getestet 😅 brauchen wir 'valuesByMode' dann überhaupt noch hier?

2023-12-27 10:46 UTC, timcreatedit commented on lib/src/domain/providers/generator_providers.dart
> +Iterable<ThemeClassGenerator> _createGeneratorsByFile({
Warum top level function? Das machst du jetzt irgendwie öfter kommt mir vor, hat das einen Grund?

2023-12-27 10:46 UTC, timcreatedit commented on lib/src/domain/providers/generator_providers.dart
> +Iterable<ThemeClassGenerator> _createGeneratorsByFile({
Ich persönlich fänd das in einer eigenen Klasse oder innerhalb eines providers besser, dann könnte man es auch mocken. Hier sinds irgendwie super viele Entscheidungen und logik

2023-12-27 10:46 UTC, timcreatedit commented on lib/src/domain/providers/generator_providers.dart
> +            "${type.className}${tokensEntry.key.toTitleCase()}",
Die Logik kann man auslagern, das passiert in der Funktion paar mal

2023-12-27 10:46 UTC, timcreatedit commented on lib/src/domain/providers/generator_providers.dart
> +    );
Wiederholt sich auch

2023-12-27 10:46 UTC, timcreatedit commented on lib/src/domain/util/token_filter_x.dart
> +            if (token.valuesByModeName[mode] case final alias?)
s.o. verstehe nicht warum wir `valuesByMode` dann noch brauchen und nicht einfach `valuesByMode` fixen so wies gedacht war und statt IDs bei Variables den Mode name nehmen.

2023-12-28 09:02 UTC, JesperBllnbm commented on lib/src/domain/models/style/design_style.dart
> +  String get collectionName => name.split('/').first;
Also was ich ganz cool fände wenn man Styles und Variablen am Ende in einer Klasse mischen kann. Ich würde sowas vorschlagen:
```Dart
 String get collectionName =>name.contains('/') ?  name.split('/').first : '';
```

2023-12-28 09:06 UTC, JesperBllnbm commented on lib/src/domain/models/variable/variable.dart
> +      );
hmm hab nichts konkretes im Kopf. Ich kann mir aber vorstellen das wir gerade noch irgendwas übersehen warum man die IDs dann doch wieder braucht. Vielleicht erstmal so lassen und wenn uns nach ein paar Wochen Verwendung nichts einfällt dann rausnehmen?

2023-12-28 10:03 UTC, JesperBllnbm commented on lib/src/domain/providers/generator_providers.dart
> +Iterable<ThemeClassGenerator> _createGeneratorsByFile({
Ja ich kann es wieder in den Provider packen. Ich verstehe nicht ganz den Unterschied - wird beim mocked nicht so oder so der ganze Provider "ausgetauscht"?

2023-12-28 10:06 UTC, JesperBllnbm commented on lib/src/domain/providers/generator_providers.dart
> +            "${type.className}${tokensEntry.key.toTitleCase()}",
Meinst du sowas in die Richtung? 

```Dart
Iterable<ThemeClassGenerator> _createGenerators(
  List<DesignToken> tokens,
  TokenFileType type,
  ThemeClassGenerator Function(MapEntry<String, Iterable<DesignToken>>) generatorFunction,
) {
  final groupedTokens = groupBy(tokens, (DesignToken dt) => dt.collectionName);
  return groupedTokens.entries.map(generatorFunction);
}
```

2023-12-28 10:07 UTC, JesperBllnbm commented on lib/src/domain/providers/generator_providers.dart
> +            "${type.className}${tokensEntry.key.toTitleCase()}",
Hab das Gefühl so wird es eigentlich nicht besser, aber vielleicht meintest du ja was anderes?

2023-12-28 10:16 UTC, JesperBllnbm commented on lib/src/domain/providers/generator_providers.dart
> +    );
Steh auch auf dem Schlauch - müssen wir das nicht fuer jede Kategorie von tokens wiederholen? Oder meintest du eine Loesung wie oben?

2023-12-28 10:18 UTC, JesperBllnbm commented on lib/src/domain/util/token_filter_x.dart
> +            if (token.valuesByModeName[mode] case final alias?)
auch s.o. - kann meiner Meinung nach in Zukunft vermutlich raus

2023-12-28 11:24 UTC, JesperBllnbm commented on lib/src/commands/shared/generation_notifier.dart
> +
Hab in einen eigenen Provider gesteckt

2024-01-05 09:38 UTC, timcreatedit commented on lib/src/domain/providers/generator_providers.dart
> +    );
Vllt machen wirs wann anders schöner

2024-01-05 09:38 UTC, timcreatedit commented on lib/src/domain/providers/generator_providers.dart
> +Iterable<ThemeClassGenerator> _createGeneratorsByFile({
Also die Funktion ist ja jetzt weder unit-testbar noch können wir sie Mocken wenn wir die Logik testen wollen, die ihr Ergebnis benutzt. Letzteres ist momentan egal weil sie nur in dem einen Provider benutzt wird, der basically nichts anderes macht, aber wenn das so bleibt könnte es ja der Provider sein, und wenn sie noch mehr uses bekäme müsste sie wiederum unit testbar sein. Ist aber jetzt auch nicht so schlimm, lass es ruhig so ich find top-level functions nur irgendwie ein weirdes pattern

2024-01-05 09:38 UTC, timcreatedit commented on lib/src/domain/providers/generator_providers.dart
> +    );
Können wir wann anders refactorn

2024-01-05 09:39 UTC, timcreatedit commented on lib/src/domain/util/token_filter_x.dart
> +            if (token.valuesByModeName[mode] case final alias?)
Wenns raus kann würd ichs raus nehmen und den anderen wieder umbenennen

2024-01-05 09:40 UTC, timcreatedit commented on lib/src/domain/util/token_filter_x.dart
> +            if (token.valuesByModeName[mode] case final alias?)
Ist ja nicht so als würde das viel Aufwand sein das wieder hinzuzufügen wenns nötig ist, und so vergessen wir 100% das rauszunehmen

2024-04-15 14:10 UTC, timcreatedit approved these changes

2024-04-15 14:13 UTC, merged