feat: basic figma variables api
whynotmake-it/figmage pull request #7
Opened 2023-10-05 21:21 UTC by JesperBllnbm

- [x] My PR title is in the style of [conventional commits](https://www.conventionalcommits.org/)
- [ ] All public facing APIs are doccumented with [dartdoc](https://dart.dev/guides/language/effective-dart/documentation)
- [x] I have added tests to cover my changes

2023-10-06 09:10 UTC, timcreatedit requested changes
Mega nice, würde nur noch die Tests umstrukturieren, ansonsten awesome! ❤️

2023-10-06 09:10 UTC, timcreatedit commented on packages/figma_variables_api/lib/src/client.dart
> +const bool kIsWeb = identical(0, 0.0);
fml so funktioniert das? 🥲

2023-10-06 09:10 UTC, timcreatedit commented on packages/figma_variables_api/test/src/dto_test.dart
> +    test('Variable deserialization and serialization', () {
Es ist ein bisschen üblicher die Gruppen nach Klassen und Membern zu strukturieren also quasi group('ClassName') -> group('fromJson') -> test('works for valid json') && test('throws for invalid json') 

so hat man dann einen näheren Match und es ist bisschen einfacher die coverage im überblick zu behalten und zu verstehen

2023-10-09 16:44 UTC, timcreatedit approved these changes
Sehr nice!

2023-10-09 16:44 UTC, timcreatedit commented on packages/figma_variables_api/pubspec.yaml
> +  mockito: ^5.4.2
hier war ja eigentlich schon die `mocktail` dependency aber lasse mich auch auf `mockito` ein. Ich persönlich find mocktail bisschen safer weil es keine code generation braucht, aber ist bisschen mehr händisches Setup. Hab mich noch nie selbst mit mockito beschäftigt :) aber glaub wir sollten uns auf jeden Fall auf eins festlegen

2023-10-21 16:14 UTC, JesperBllnbm commented
Ich mach den hier zu - habe die API jetzt ja auch in dem anderen nochmal angefasst, da ist jetzt alles drinnen

2023-10-21 16:14 UTC, closed without merging