feat: variables repo & model & convert aliases
whynotmake-it/figmage pull request #9
Opened 2023-10-08 18:38 UTC by JesperBllnbm

Ist vielleicht noch bisschen rough around the edges aber ich glaube es macht Sinn jetzt mal zusammen drauf zu schauen :)

- [x] My PR title is in the style of [conventional commits](https://www.conventionalcommits.org/)
- [x] All public facing APIs are doccumented with [dartdoc](https://dart.dev/guides/language/effective-dart/documentation)
- [x] I have added tests to cover my changes

2023-10-09 17:07 UTC, timcreatedit requested changes
Thank youuu

2023-10-09 17:07 UTC, timcreatedit commented on lib/src/domain/models/variable/variable.dart
> +    switch (json['resolvedType'] as String) {
das lässt sich auch per freezed annotations abbilden glaub ich.

Beispiel aus dem freezed Readme:
```dart
@Freezed(unionKey: 'type', unionValueCase: FreezedUnionCase.pascal)
sealed class MyResponse with _$MyResponse {
  const factory MyResponse(String a) = MyResponseData;

  @FreezedUnionValue('SpecialCase')
  const factory MyResponse.special(String a, int b) = MyResponseSpecial;

  const factory MyResponse.error(String message) = MyResponseError;

  // ...
}
```

2023-10-09 17:07 UTC, timcreatedit commented on lib/src/domain/models/variable/variable.dart
> +    @JsonKey(fromJson: _boolMap)
die conversion functions würd ich persönlich `_boolMapFromJson` nennen, aber not important

2023-10-09 17:07 UTC, timcreatedit commented on lib/src/domain/models/variable/variable.dart
> +    required Map<String, VariableValue> valuesByMode,
Wenn `VariableValue` eine union ist, warum können wir hier nicht `BooleanValue` nehmen?

2023-10-09 17:07 UTC, timcreatedit commented on lib/src/domain/models/variable/variable_value/variable_value.dart
> +@Freezed(fromJson: true, toJson: true)
Sollte hier `fromJson` nicht `false` sein? Gibt zumindest keine factory

2023-10-09 17:07 UTC, timcreatedit commented on mason-lock.json
> +{"bricks":{}}
das file würd ich löschen

2023-10-09 17:07 UTC, timcreatedit commented on mason.yaml
> +# Register bricks which can be consumed via the Mason CLI.
hier nix drin also kann raus

2023-10-09 17:08 UTC, timcreatedit commented on mason.yaml
> +# Register bricks which can be consumed via the Mason CLI.
Also das file

2023-10-10 09:26 UTC, JesperBllnbm commented on lib/src/domain/models/variable/variable.dart
> +    required Map<String, VariableValue> valuesByMode,
Weil es auch ein VariableAliasValue sein kann 😿

2023-10-10 09:26 UTC, JesperBllnbm commented on lib/src/domain/models/variable/variable.dart
> +    switch (json['resolvedType'] as String) {
true that

2023-10-10 09:26 UTC, JesperBllnbm commented on lib/src/domain/models/variable/variable_value/variable_value.dart
> +@Freezed(fromJson: true, toJson: true)
Das geht beides. Hier aus der Doku:
  /// Whether to generate a `fromJson` or not
  ///
  /// If null, picks up the default values from the project's `build.yaml`.
  ///
  /// If that value is null too, will be inferred based on whether the Freezed
  /// class has a `fromJson` constructor`, such that
  ///

2023-10-10 09:26 UTC, JesperBllnbm commented on mason-lock.json
> +{"bricks":{}}
👍

2023-10-10 09:26 UTC, JesperBllnbm commented on mason.yaml
> +# Register bricks which can be consumed via the Mason CLI.
👍

2023-10-10 09:26 UTC, JesperBllnbm commented on lib/src/data/repositories/figma_variables_repository.dart
> +      getVariableValues<T extends VariableValue>({
👍

2023-10-10 09:27 UTC, JesperBllnbm commented on lib/src/data/repositories/figma_variables_repository.dart
> +  Map<String, Map<String, T>> createValueModeMap<T extends VariableValue>({
visibleForTesting

2023-10-10 09:28 UTC, JesperBllnbm commented on lib/src/data/repositories/figma_variables_repository.dart
> +
`
    final Map<String, Variable> cleanedVariables = Map.from(variables);
    if (T == BooleanValue) {
      cleanedVariables
          .removeWhere((key, variable) => variable is! BooleanVariable);
`

2023-10-10 09:28 UTC, timcreatedit commented on lib/src/domain/models/variable/variable_value/variable_value.dart
> +@Freezed(fromJson: true, toJson: true)
Checke nicht warum das dann da steht?

2023-10-10 09:31 UTC, timcreatedit commented on lib/src/data/repositories/figma_variables_repository.dart
> +                : throw TypeError();
Ja das ist die Pattern Matching syntax die ist bisschen painful. Ist nicht wirklich der Konstruktor, man muss es sich eher als Schablone vorstellen. Man kann ja zum Beispiel auch sowas machen wie 

```dart
final resultValue = switch(value) {
    BooleanValue(value: true) => throw "Beispiel",
    T() => value,
    VariableAliasValue() => _getVariableModeValueRecursive<T>(alias: value, variables: variables,),
    _ => throw TypeError(),
};
```

2023-10-10 09:31 UTC, timcreatedit commented on lib/src/data/repositories/figma_variables_repository.dart
> +      variable.valuesByMode.forEach((modeId, value) {
Ach so der ansatz wär nur fürs innere

2023-10-10 09:33 UTC, timcreatedit commented on lib/src/data/repositories/figma_variables_repository.dart
> +
Nice, kann man jetzt das?

```dart
cleanedVariables
          .removeWhere((key, variable) => variable is! T);
```

2023-10-10 09:36 UTC, timcreatedit commented on lib/src/domain/models/variable/variable.dart
> +    required Map<String, VariableValue> valuesByMode,
Hab das Gefühl wir sollten das irgendwie anders modellieren dann, aber hab keine Zeit drüber nachzudenken grad. Könnte man vllt eine Klasse haben:

```dart
class AliasOr<T> {

}
```

für jeden typen, dann könnte man hier `Map<String, AliasOr<BooleanValue>>`? Geht bestimmt nicht 1:1 so aber verstehst du meinen Ansatz?

2023-10-10 09:45 UTC, JesperBllnbm commented on lib/src/domain/models/variable/variable_value/variable_value.dart
> +@Freezed(fromJson: true, toJson: true)
Weil sonst die to und fromJson fehlt. Also ich mein entweder schreibt man die Factory oder man annontiert einfach mit true. Wir brauchen die from und toJson ja fuer Variable.fromJson

2023-10-10 09:45 UTC, JesperBllnbm commented on lib/src/domain/models/variable/variable_value/variable_value.dart
> +@Freezed(fromJson: true, toJson: true)
Aber hab das Gefühl wir sprechen aneinander vorbei?

2023-10-10 09:57 UTC, timcreatedit commented on lib/src/domain/models/variable/variable_value/variable_value.dart
> +@Freezed(fromJson: true, toJson: true)
Ah ich glaub ich checks? Wir wollen nur die einzelnen union cases `fromJson` machen können? Weil `VariableValue.fromJson(...)` geht ja so nicht

2023-11-10 21:55 UTC, timcreatedit approved these changes
🧙

2023-11-10 21:55 UTC, timcreatedit commented on packages/figma_variables_api/lib/src/models/dto/variable_mode/variable_mode_dto.dart
>  @CopyWith()
Freezed

2023-11-10 23:41 UTC, merged